# Generated by Django 5.2.12 on 2026-03-06 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sensor_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique sensor identifier (e.g., LIVING_ROOM_01)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Human-readable name", max_length=128
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        db_index=True,
                        help_text="Physical location (e.g., Living Room, Kitchen)",
                        max_length=128,
                    ),
                ),
                (
                    "sensor_type",
                    models.CharField(
                        default="environmental",
                        help_text="Type: environmental, air_quality, hvac, contact",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="active",
                        help_text="Current operational status",
                        max_length=20,
                    ),
                ),
                (
                    "installed_at",
                    models.DateTimeField(
                        blank=True, help_text="Installation date", null=True
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True, help_text="Last successful data receipt", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible sensor-specific config (e.g., calibration offsets)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["location", "sensor_id"],
                "indexes": [
                    models.Index(
                        fields=["status", "sensor_type"],
                        name="sensor_sens_status_2c7240_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sensor_id_raw",
                    models.CharField(
                        db_index=True,
                        help_text="Raw sensor_id from import (persistent link)",
                        max_length=64,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="Sensor reading timestamp"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was ingested"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True, help_text="Temperature in Celsius", null=True
                    ),
                ),
                (
                    "humidity",
                    models.FloatField(
                        blank=True, help_text="Relative humidity percentage", null=True
                    ),
                ),
                (
                    "co2_ppm",
                    models.FloatField(
                        blank=True, help_text="CO2 concentration in ppm", null=True
                    ),
                ),
                (
                    "battery_level",
                    models.FloatField(
                        blank=True, help_text="Battery level percentage", null=True
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Has passed all validation checks",
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        default=100.0, help_text="Overall quality score (0-100)"
                    ),
                ),
                (
                    "quality_flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of quality issues: ['outlier', 'stuck_at', 'range_violation']",
                    ),
                ),
                (
                    "is_raw",
                    models.BooleanField(
                        default=True,
                        help_text="True if unprocessed, False if normalized/derived",
                    ),
                ),
                (
                    "processing_notes",
                    models.TextField(
                        blank=True, help_text="Notes from data processing pipeline"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked sensor (nullable for raw imports)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="readings",
                        to="sensor.sensor",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DataQualityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sensor_id",
                    models.CharField(
                        db_index=True, help_text="Sensor identifier", max_length=64
                    ),
                ),
                (
                    "detection_type",
                    models.CharField(
                        choices=[
                            ("range_check", "Range Validation"),
                            ("stuck_at", "Stuck-at Detection"),
                            ("outlier", "Statistical Outlier"),
                            ("gap", "Time Gap Detection"),
                            ("duplicate", "Duplicate Detection"),
                        ],
                        help_text="Type of quality check",
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        help_text="Severity level",
                        max_length=16,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the issue"
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (e.g., expected_range, detected_value)",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this issue was detected"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this issue was resolved/reviewed",
                        null=True,
                    ),
                ),
                (
                    "reading",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated reading",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_logs",
                        to="sensor.sensorreading",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(
                fields=["sensor_id_raw", "-timestamp"],
                name="sensor_sens_sensor__d48b5b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(
                fields=["is_validated", "-timestamp"],
                name="sensor_sens_is_vali_9b2fa2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(
                fields=["timestamp", "sensor_id_raw"],
                name="sensor_sens_timesta_f432e8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sensorreading",
            constraint=models.UniqueConstraint(
                fields=("sensor_id_raw", "timestamp"),
                name="unique_sensor_reading_per_timestamp",
            ),
        ),
        migrations.AddIndex(
            model_name="dataqualitylog",
            index=models.Index(
                fields=["sensor_id", "detection_type"],
                name="sensor_data_sensor__8a8c88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataqualitylog",
            index=models.Index(
                fields=["severity", "-detected_at"],
                name="sensor_data_severit_83ef35_idx",
            ),
        ),
    ]
